---
name: layout_example
description: "A Flutter project example to provide examples about layout in Flutter."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+1

environment:
  sdk: ^3.9.2

dependencies:
  cupertino_icons: ^1.0.8

  flutter:
    sdk: flutter
  http: ^1.5.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.10.1
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter

  json_serializable: ^6.11.1
  very_good_analysis: ^10.0.0

flutter:
  uses-material-design: true

